### PR TITLE
Icon Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icon isn't good. Aside from the random placement of network symbol and shadow at the ceiling, It doesn't comply by [eOS HIG](https://elementary.io/docs/human-interface-guidelines#shadows) as well.

### CODE REVIEW

**Comment by torikulhabib** [comment]
Screenshot from 2019-08-05 18-15-13
the icon seems too small can you fix it.

**Comment by Fatih20** [comment]
I'll get on it.

**Comment by Fatih20** [comment]
Done.

**Comment by torikulhabib** [comment]
thanks

**Comment by Fatih20** [comment]
You're welcome! I'm from Indonesia too by the way.

**Comment by torikulhabib** [comment]
kota asal mana bro.

**Comment by Fatih20** [comment]
Surabaya.

**Pull request merged**
